### ISSUE TITLE
Allow configuration of runner url

### ISSUE THREAD

**Issue by honsq90** [DevExpress/testcafe-studio-docs#100]
I hope this is the right place to reach out, let me know if it isn't.

Similar to how we might do `createTestCafe('localhost', 1337, 1338)` in [the Runner class](http://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html), it'd be good if we could do the same in TestCafe Studio.

The default IP address that is picked up at the moment isn't always accessible due to internal network configurations. At the very least, it'd be good to support localhost to start with.

**Comment by kirovboris** [comment]
Hi @honsq90, 

Thank you for your interest in TestCafe Studio!
This functionality will be included in the release version.
